# docker-compose.yml
version: "3.8"

services:
  processor:
    build: .
    container_name: processor_instance
    environment:
      - TELEGRAM_API_ID=your_api_id_here
      - TELEGRAM_API_HASH=your_api_hash_here
      - TELEGRAM_SESSION_STRING=your_session_string_here
    volumes:
      - ./data/instance_1:/app/data
    restart: always

  bot:
    build: .
    container_name: bot_instance
    command: python bot/interface.py
    environment:
      - TELEGRAM_BOT_TOKEN=your_bot_token_here
    volumes:
      - ./data/instance_1:/app/data
    restart: always

  # Optionally, add your web app service here
  web:
    build: ./web
    container_name: web_instance
    ports:
      - "8000:8000"
    volumes:
      - ./data/instance_1:/app/data
    restart: always
