import { NextResponse } from "next/server"

const workflowTemplates = [
  {
    id: "social_media_bot",
    name: "Social Media Bot",
    description: "AI-powered social media content creation and posting",
    category: "social",
    features: [
      "Automated content generation",
      "Duplicate detection",
      "Sentiment analysis",
      "Media attachment support",
      "Engagement tracking",
    ],
    configFields: [
      {
        name: "posting_interval",
        type: "number",
        label: "Posting Interval (seconds)",
        description: "Time between posts in seconds",
        required: true,
        defaultValue: 3600,
      },
      {
        name: "max_posts_per_hour",
        type: "number",
        label: "Max Posts Per Hour",
        description: "Maximum number of posts per hour",
        required: true,
        defaultValue: 5,
      },
      {
        name: "generation_model",
        type: "select",
        label: "Generation Model",
        description: "AI model for content generation",
        required: true,
        defaultValue: "gpt-4",
        options: ["gpt-4", "gpt-3.5-turbo", "claude-3", "gemini-pro"],
      },
      {
        name: "filter_model",
        type: "select",
        label: "Filter Model",
        description: "AI model for content filtering",
        required: true,
        defaultValue: "gpt-3.5-turbo",
        options: ["gpt-4", "gpt-3.5-turbo", "claude-3", "gemini-pro"],
      },
      {
        name: "sentiment_threshold",
        type: "number",
        label: "Sentiment Threshold",
        description: "Minimum sentiment score (0.0 to 1.0)",
        required: true,
        defaultValue: 0.7,
      },
      {
        name: "duplicate_check_enabled",
        type: "boolean",
        label: "Enable Duplicate Check",
        description: "Check for duplicate content before posting",
        required: false,
        defaultValue: true,
      },
      {
        name: "topics",
        type: "textarea",
        label: "Topics of Interest",
        description: "Topics to focus on (one per line)",
        required: true,
        defaultValue: "Technology\nArtificial Intelligence\nStartups",
      },
      {
        name: "api_keys",
        type: "textarea",
        label: "API Keys Configuration",
        description: "API keys and tokens (JSON format)",
        required: true,
        defaultValue: '{\n  "twitter_api_key": "",\n  "openai_api_key": ""\n}',
      },
    ],
  },
  {
    id: "crypto_trading_bot",
    name: "Crypto Trading Analysis Bot",
    description: "Cryptocurrency market analysis and trading signals",
    category: "trading",
    features: [
      "Real-time market analysis",
      "Volume and liquidity tracking",
      "Technical indicators",
      "Risk assessment",
      "Multi-exchange support",
    ],
    configFields: [
      {
        name: "trading_pairs",
        type: "textarea",
        label: "Trading Pairs",
        description: "Cryptocurrency pairs to monitor (one per line)",
        required: true,
        defaultValue: "BTC/USDT\nETH/USDT\nSOL/USDT",
      },
      {
        name: "analysis_interval",
        type: "number",
        label: "Analysis Interval (seconds)",
        description: "How often to analyze market data",
        required: true,
        defaultValue: 1800,
      },
      {
        name: "price_change_threshold",
        type: "number",
        label: "Price Change Threshold (%)",
        description: "Minimum price change to trigger analysis",
        required: true,
        defaultValue: 5.0,
      },
      {
        name: "volume_analysis_enabled",
        type: "boolean",
        label: "Enable Volume Analysis",
        description: "Include volume data in analysis",
        required: false,
        defaultValue: true,
      },
      {
        name: "exchanges",
        type: "select",
        label: "Primary Exchange",
        description: "Main exchange for data",
        required: true,
        defaultValue: "binance",
        options: ["binance", "coinbase", "kraken", "bybit", "okx"],
      },
      {
        name: "risk_level",
        type: "select",
        label: "Risk Level",
        description: "Risk tolerance for signals",
        required: true,
        defaultValue: "medium",
        options: ["low", "medium", "high"],
      },
    ],
  },
  {
    id: "news_curator_bot",
    name: "News Curator Bot",
    description: "Automated news aggregation and summarization",
    category: "news",
    features: [
      "Multi-source news aggregation",
      "AI-powered summarization",
      "Topic categorization",
      "Trending detection",
      "Custom RSS feeds",
    ],
    configFields: [
      {
        name: "news_sources",
        type: "textarea",
        label: "News Sources",
        description: "RSS feeds or news APIs (one per line)",
        required: true,
        defaultValue: "https://feeds.reuters.com/reuters/technologyNews\nhttps://rss.cnn.com/rss/edition.rss",
      },
      {
        name: "update_frequency",
        type: "number",
        label: "Update Frequency (minutes)",
        description: "How often to check for new articles",
        required: true,
        defaultValue: 30,
      },
      {
        name: "summary_length",
        type: "select",
        label: "Summary Length",
        description: "Length of article summaries",
        required: true,
        defaultValue: "medium",
        options: ["short", "medium", "long"],
      },
      {
        name: "categories",
        type: "textarea",
        label: "Categories",
        description: "News categories to focus on (one per line)",
        required: true,
        defaultValue: "Technology\nBusiness\nScience\nPolitics",
      },
      {
        name: "language",
        type: "select",
        label: "Language",
        description: "Primary language for content",
        required: true,
        defaultValue: "english",
        options: ["english", "spanish", "french", "german", "chinese"],
      },
    ],
  },
]

export async function GET() {
  return NextResponse.json(workflowTemplates)
}
